extends Node

signal on_game_start()
signal on_player_damage(player, source)
signal on_player_death(player, source)
signal on_ally_damage(entity, source)
signal on_ally_death(entity, source)
signal on_enemy_damage(entity, source)
signal on_enemy_death(entity, source)
signal on_room_capture(room)
signal on_outpost_capture(outpost)
signal on_party_kill(party)
signal on_entity_spawn(entity)
signal on_room_enter(room)
signal on_room_exit(room)
signal on_new_objective(objective)
signal on_objective_update(objective, progress)
signal on_objective_complete(objective)
signal on_boss_start()
